apiVersion: v1
kind: Secret
metadata:
  name: opnsense-api
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  key: {{ .Values.opnsense.apiKey | quote }}
  secret: {{ .Values.opnsense.apiSecret | quote }}
